import type { Catalog, Proverb, ProverbId } from "./proverb";

function proverbId(text: string): ProverbId {
  const id = text
    .normalize("NFKD")
    .toLowerCase()
    .replace(/'/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (!id) throw new Error("proverb id is empty");
  return id as ProverbId;
}

export function createCatalog(rows: ReadonlyArray<{ text: string; origin: string }>): Catalog {
  if (rows.length === 0) throw new Error("catalog must not be empty");
  const ids = new Set<string>();
  const texts = new Set<string>();
  const proverbs: Proverb[] = [];
  for (const row of rows) {
    const text = row.text.trim();
    const origin = row.origin.trim();
    if (!text) throw new Error("proverb text is empty");
    if (!origin) throw new Error("proverb origin is empty");
    if (texts.has(text)) throw new Error(`duplicate proverb text: ${text}`);
    const id = proverbId(text);
    if (ids.has(id)) throw new Error(`duplicate proverb id: ${id}`);
    ids.add(id);
    texts.add(text);
    proverbs.push({ id, text, origin });
  }
  const [first, ...rest] = proverbs;
  if (!first) throw new Error("catalog must not be empty");
  return [first, ...rest];
}

const ENTRIES = [
  ["A bad workman blames his tools", "English"],
  ["A bird in the hand is worth two in the bush", "English"],
  ["A burnt child dreads the fire", "English"],
  ["A cat has nine lives", "English"],
  ["A chain is only as strong as its weakest link", "English"],
  ["A change is as good as a rest", "English"],
  ["A closed mouth catches no flies", "English"],
  ["A drowning man will clutch at a straw", "English"],
  ["A fool and his money are soon parted", "English"],
  ["A fool at forty is a fool indeed", "English"],
  ["A friend in need is a friend indeed", "English"],
  ["A friend's dinner is soon dished", "Scottish"],
  ["A golden key can open any door", "English"],
  ["A good beginning makes a good ending", "English"],
  ["A good name is better than riches", "English"],
  ["A green Yule makes a fat kirkyard", "Scottish"],
  ["A house divided against itself cannot stand", "English"],
  ["A hungry man is an angry man", "English"],
  ["A leopard cannot change its spots", "English"],
  ["A little learning is a dangerous thing", "English"],
  ["A man is known by the company he keeps", "English"],
  ["A miss is as good as a mile", "English"],
  ["A new broom sweeps clean", "English"],
  ["A nod is as good as a wink to a blind horse", "English"],
  ["A penny saved is a penny earned", "English"],
  ["A place for everything and everything in its place", "English"],
  ["A rolling stone gathers no moss", "English"],
  ["A soft answer turns away wrath", "English"],
  ["A sound mind in a sound body", "Latin"],
  ["A stitch in time saves nine", "English"],
  ["A watched pot never boils", "English"],
  ["A word to the wise is enough", "Latin"],
  ["Absence makes the heart grow fonder", "English"],
  ["Accidents will happen", "English"],
  ["Actions speak louder than words", "English"],
  ["After a storm comes a calm", "English"],
  ["After dinner rest a while, after supper walk a mile", "English"],
  ["All cats are grey in the dark", "English"],
  ["All good things must come to an end", "English"],
  ["All is fish that comes to the net", "English"],
  ["All is grist that comes to the mill", "English"],
  ["All roads lead to Rome", "English"],
  ["All that glitters is not gold", "English"],
  ["All things come to those who wait", "English"],
  ["All work and no play makes Jack a dull boy", "English"],
  ["All's fair in love and war", "English"],
  ["All's well that ends well", "English"],
  ["An apple a day keeps the doctor away", "English"],
  ["An empty sack cannot stand upright", "English"],
  ["An Englishman's home is his castle", "English"],
  ["An honest man's word is as good as his bond", "English"],
  ["An ounce of prevention is worth a pound of cure", "English"],
  ["Any port in a storm", "English"],
  ["Appearances can be deceptive", "English"],
  ["April showers bring May flowers", "English"],
  ["Art is long, life is short", "Latin"],
  ["As well be hanged for a sheep as a lamb", "English"],
  ["As you sow, so shall you reap", "English"],
  ["Ask no questions and hear no lies", "English"],
  ["Barking dogs seldom bite", "English"],
  ["Beauty is in the eye of the beholder", "English"],
  ["Beauty is only skin deep", "English"],
  ["Beggars cannot be choosers", "English"],
  ["Better a living dog than a dead lion", "English"],
  ["Better a wee bush than nae bield", "Scottish"],
  ["Better be envied than pitied", "English"],
  ["Better be the head of a dog than the tail of a lion", "English"],
  ["Better late than never", "English"],
  ["Better rue sit than rue flit", "Scottish"],
  ["Better safe than sorry", "English"],
  ["Better the devil you know than the devil you don't", "English"],
  ["Better to wear out than to rust out", "English"],
  ["Between the devil and the deep blue sea", "English"],
  ["Between two stools one falls to the ground", "English"],
  ["Beware of Greeks bearing gifts", "Latin"],
  ["Big fish eat little fish", "English"],
  ["Birds of a feather flock together", "English"],
  ["Blood is thicker than water", "English"],
  ["Boys will be boys", "English"],
  ["Bread is the staff of life", "English"],
  ["Business before pleasure", "English"],
  ["Caesar's wife must be above suspicion", "Latin"],
  ["Call a spade a spade", "English"],
  ["Cauld kail het again", "Scottish"],
  ["Charity begins at home", "English"],
  ["Cheats never prosper", "English"],
  ["Chickens come home to roost", "English"],
  ["Children should be seen and not heard", "English"],
  ["Christmas comes but once a year", "English"],
  ["Civility costs nothing", "English"],
  ["Cleanliness is next to godliness", "English"],
  ["Clothes make the man", "English"],
  ["Comparisons are odious", "English"],
  ["Confession is good for the soul", "English"],
  ["Constant dropping wears away a stone", "Latin"],
  ["Courtesy costs nothing", "English"],
  ["Cross the stream where it is shallowest", "English"],
  ["Curiosity killed the cat", "English"],
  ["Cut your coat according to your cloth", "English"],
  ["Dead men tell no tales", "English"],
  ["Desperate diseases must have desperate remedies", "English"],
  ["Diligence is the mother of good fortune", "English"],
  ["Dinnae teach yer granny to sook eggs", "Scottish"],
  ["Discretion is the better part of valour", "English"],
  ["Divide and rule", "Latin"],
  ["Do as I say, not as I do", "English"],
  ["Do as you would be done by", "English"],
  ["Do unto others as you would have them do unto you", "English"],
  ["Don't bite off more than you can chew", "English"],
  ["Don't bite the hand that feeds you", "English"],
  ["Don't burn your boats", "English"],
  ["Don't burn your bridges", "English"],
  ["Don't count your chickens before they hatch", "English"],
  ["Don't cross the bridge until you come to it", "English"],
  ["Don't cry over spilled milk", "English"],
  ["Don't cut off your nose to spite your face", "English"],
  ["Don't halloo until you are out of the wood", "English"],
  ["Don't hide your light under a bushel", "English"],
  ["Don't judge a book by its cover", "English"],
  ["Don't let the grass grow under your feet", "English"],
  ["Don't look a gift horse in the mouth", "English"],
  ["Don't make a mountain out of a molehill", "English"],
  ["Don't make a rod for your own back", "English"],
  ["Don't put all your eggs in one basket", "English"],
  ["Don't put new wine into old bottles", "English"],
  ["Don't put the cart before the horse", "English"],
  ["Don't shoot the messenger", "English"],
  ["Don't spoil the ship for a ha'p'orth of tar", "English"],
  ["Don't throw good money after bad", "English"],
  ["Don't throw pearls before swine", "English"],
  ["Don't throw the baby out with the bathwater", "English"],
  ["Don't upset the apple cart", "English"],
  ["Don't wash your dirty linen in public", "English"],
  ["Dreams go by contraries", "English"],
  ["Each to his own", "English"],
  ["Eagles do not catch flies", "Latin"],
  ["Early to bed and early to rise makes a man healthy, wealthy, and wise", "English"],
  ["East, west, home's best", "English"],
  ["Easier said than done", "English"],
  ["Easy come, easy go", "English"],
  ["Eat, drink, and be merry, for tomorrow we die", "English"],
  ["Eaten bread is soon forgotten", "English"],
  ["Empty vessels make the most sound", "English"],
  ["Enough is as good as a feast", "English"],
  ["Even Homer sometimes nods", "Latin"],
  ["Even a worm will turn", "English"],
  ["Every cloud has a silver lining", "English"],
  ["Every dog has his day", "English"],
  ["Every dog is allowed one bite", "English"],
  ["Every Jack has his Jill", "English"],
  ["Every little helps", "English"],
  ["Every man for himself", "English"],
  ["Every man has his price", "English"],
  ["Every man is the architect of his own fortune", "Latin"],
  ["Every rose has its thorn", "English"],
  ["Every tide has its ebb", "English"],
  ["Everybody's business is nobody's business", "English"],
  ["Example is better than precept", "English"],
  ["Experience is the best teacher", "English"],
  ["Experience keeps a dear school", "English"],
  ["Experience teaches", "Latin"],
  ["Facts are chiels that winna ding", "Scottish"],
  ["Facts are stubborn things", "English"],
  ["Faint heart never won fair lady", "English"],
  ["Fair exchange is no robbery", "English"],
  ["Faith will move mountains", "English"],
  ["Familiarity breeds contempt", "English"],
  ["Fast bind, fast find", "English"],
  ["Feed a cold, starve a fever", "English"],
  ["Fields have eyes, and woods have ears", "English"],
  ["Fight fire with fire", "English"],
  ["Finders keepers, losers weepers", "English"],
  ["Fine feathers make fine birds", "English"],
  ["Fine words butter no parsnips", "English"],
  ["Fire is a good servant but a bad master", "English"],
  ["First catch your hare", "English"],
  ["First come, first served", "English"],
  ["First impressions are the most lasting", "English"],
  ["First things first", "English"],
  ["Fish and guests stink after three days", "English"],
  ["Fish rot from the head down", "English"],
  ["Fools and bairns should never see half-done work", "Scottish"],
  ["Fools rush in where angels fear to tread", "English"],
  ["Forbidden fruit is the sweetest", "English"],
  ["Forewarned is forearmed", "English"],
  ["Forgive and forget", "English"],
  ["Fortune favors the bold", "Latin"],
  ["Four eyes see more than two", "English"],
  ["From clogs to clogs in three generations", "English"],
  ["From hardship to the stars", "Latin"],
  ["Give a man enough rope and he will hang himself", "English"],
  ["Give credit where credit is due", "English"],
  ["Give the devil his due", "English"],
  ["Go abroad and you'll hear news of home", "English"],
  ["God helps those who help themselves", "English"],
  ["Good fences make good neighbors", "English"],
  ["Good wine needs no bush", "English"],
  ["Grasp all, lose all", "English"],
  ["Great oaks from little acorns grow", "English"],
  ["Great talkers are little doers", "English"],
  ["Guid gear comes in sma' bulk", "Scottish"],
  ["Half a loaf is better than no bread", "English"],
  ["Handsome is as handsome does", "English"],
  ["Hard cases make bad law", "English"],
  ["Haste makes waste", "English"],
  ["He conquers who conquers himself", "Latin"],
  ["He gives twice who gives quickly", "Latin"],
  ["He knows which side his bread is buttered", "English"],
  ["He laughs best who laughs last", "English"],
  ["He that cannot obey cannot command", "English"],
  ["He that fights and runs away may live to fight another day", "English"],
  ["He that tholes overcomes", "Scottish"],
  ["He that would eat the kernel must crack the nut", "English"],
  ["He who hesitates is lost", "English"],
  ["He who is his own lawyer has a fool for a client", "English"],
  ["He who pays the piper calls the tune", "English"],
  ["He who sups with the devil should have a long spoon", "English"],
  ["He who would climb the ladder must begin at the bottom", "English"],
  ["Health is better than wealth", "English"],
  ["Health is not valued till sickness comes", "English"],
  ["Hear all, see all, say nowt", "English"],
  ["Heaven protects children, sailors, and drunken men", "English"],
  ["Help a lame dog over a stile", "English"],
  ["History is the teacher of life", "Latin"],
  ["History repeats itself", "English"],
  ["Home is where the heart is", "English"],
  ["Honesty is the best policy", "English"],
  ["Honey catches more flies than vinegar", "English"],
  ["Hope deferred makes the heart sick", "English"],
  ["Hope for the best and prepare for the worst", "English"],
  ["Hope springs eternal", "English"],
  ["Hunger is the best sauce", "English"],
  ["Idle folk have the least leisure", "English"],
  ["Idle hands are the devil's workshop", "English"],
  ["If at first you don't succeed, try, try again", "English"],
  ["If ifs and ands were pots and pans, there'd be no work for tinkers", "English"],
  ["If the cap fits, wear it", "English"],
  ["If the mountain will not come to Muhammad, Muhammad must go to the mountain", "English"],
  ["If wishes were horses, beggars would ride", "English"],
  ["If you lie down with dogs, you will get up with fleas", "English"],
  ["If you play with fire you get burned", "English"],
  ["If you run after two hares you will catch neither", "English"],
  ["If you want a thing done well, do it yourself", "English"],
  ["If you want peace, prepare for war", "Latin"],
  ["Ignorance is bliss", "English"],
  ["Ignorance of the law is no excuse", "Latin"],
  ["Ill gotten goods never prosper", "English"],
  ["Ill news travels fast", "English"],
  ["Imitation is the sincerest form of flattery", "English"],
  ["In for a penny, in for a pound", "English"],
  ["In the country of the blind, the one-eyed man is king", "English"],
  ["In war, the law is silent", "Latin"],
  ["In wine there is truth", "Latin"],
  ["It is a long lane that has no turning", "English"],
  ["It is easier to pull down than to build up", "English"],
  ["It is easy to be wise after the event", "English"],
  ["It is ill waiting for dead men's shoes", "English"],
  ["It is never too late to mend", "English"],
  ["It is no use locking the stable door after the horse has bolted", "English"],
  ["It never rains but it pours", "English"],
  ["It takes all sorts to make a world", "English"],
  ["It takes two to make a quarrel", "English"],
  ["It's a lang road that's no goat a turnin", "Scottish"],
  ["It's a poor heart that never rejoices", "English"],
  ["It's a wise child that knows its own father", "English"],
  ["It's an ill wind that blows nobody any good", "English"],
  ["Jack of all trades, master of none", "English"],
  ["Keep a calm sough", "Scottish"],
  ["Keep a thing seven years and you will find a use for it", "English"],
  ["Keep no more cats than will catch mice", "English"],
  ["Keep your powder dry", "English"],
  ["Keep your shop and your shop will keep you", "English"],
  ["Know thyself", "Latin"],
  ["Knowledge is power", "Latin"],
  ["Lang may your lum reek", "Scottish"],
  ["Laugh and grow fat", "English"],
  ["Least said, soonest mended", "English"],
  ["Leave no stone unturned", "English"],
  ["Leave well alone", "English"],
  ["Lend your money and lose your friend", "English"],
  ["Let bygones be bygones", "English"],
  ["Let justice be done though the heavens fall", "Latin"],
  ["Let not the sun go down upon your wrath", "English"],
  ["Let sleeping dogs lie", "English"],
  ["Let the buyer beware", "Latin"],
  ["Let the cobbler stick to his last", "Latin"],
  ["Liars should have good memories", "English"],
  ["Life is not all beer and skittles", "English"],
  ["Life is short and time is swift", "English"],
  ["Lightning never strikes twice in the same place", "English"],
  ["Like attracts like", "English"],
  ["Like father, like son", "English"],
  ["Like master, like man", "English"],
  ["Like mother, like daughter", "English"],
  ["Listeners never hear any good of themselves", "English"],
  ["Little boats should keep near shore", "English"],
  ["Little pitchers have long ears", "English"],
  ["Little strokes fell great oaks", "English"],
  ["Little thieves are hanged, but great ones escape", "English"],
  ["Live and learn", "English"],
  ["Live and let live", "English"],
  ["Long absent, soon forgotten", "English"],
  ["Look after the pennies and the pounds will look after themselves", "English"],
  ["Look before you leap", "English"],
  ["Love and a cough cannot be hid", "English"],
  ["Love conquers all", "Latin"],
  ["Love is blind", "English"],
  ["Love laughs at locksmiths", "English"],
  ["Love me little, love me long", "English"],
  ["Love me, love my dog", "English"],
  ["Love will find a way", "English"],
  ["Lucky at cards, unlucky in love", "English"],
  ["Make a virtue of necessity", "English"],
  ["Make haste slowly", "Latin"],
  ["Make hay while the sun shines", "English"],
  ["Man does not live by bread alone", "English"],
  ["Man is a wolf to man", "Latin"],
  ["Man proposes, God disposes", "Latin"],
  ["Manners maketh man", "English"],
  ["Many a little makes a mickle", "English"],
  ["Many a mickle makes a muckle", "Scottish"],
  ["Many a true word is spoken in jest", "English"],
  ["Many hands make light work", "English"],
  ["March comes in like a lion and goes out like a lamb", "English"],
  ["Marriages are made in heaven", "English"],
  ["Marry in haste, repent at leisure", "English"],
  ["Might makes right", "English"],
  ["Misery loves company", "English"],
  ["Misfortunes never come singly", "English"],
  ["Moderation in all things", "Latin"],
  ["Money begets money", "English"],
  ["Money is a good servant but a bad master", "English"],
  ["Money isn't everything", "English"],
  ["Money talks", "English"],
  ["More haste, less speed", "English"],
  ["Much coin, much care", "English"],
  ["Murder will out", "English"],
  ["Music hath charms to soothe the savage breast", "English"],
  ["Nae man can tether time or tide", "Scottish"],
  ["Nature abhors a vacuum", "Latin"],
  ["Ne'er cast a clout till May be out", "Scottish"],
  ["Necessity is the mother of invention", "English"],
  ["Necessity knows no law", "Latin"],
  ["Needs must when the devil drives", "English"],
  ["Never put off till tomorrow what you can do today", "English"],
  ["Never say die", "English"],
  ["Never speak ill of the dead", "Latin"],
  ["Never too old to learn", "English"],
  ["Never trouble trouble till trouble troubles you", "English"],
  ["Night brings counsel", "English"],
  ["No cross, no crown", "English"],
  ["No living man all things can", "English"],
  ["No man can serve two masters", "English"],
  ["No man is an island", "English"],
  ["No man is indispensable", "English"],
  ["No man is wise at all times", "English"],
  ["No names, no pack drill", "English"],
  ["No news is good news", "English"],
  ["No one should be a judge in his own cause", "Latin"],
  ["No pain, no gain", "English"],
  ["No rest for the wicked", "English"],
  ["No rose without a thorn", "English"],
  ["No smoke without fire", "English"],
  ["No time like the present", "English"],
  ["None but the brave deserve the fair", "English"],
  ["None so blind as those who will not see", "English"],
  ["None so deaf as those who will not hear", "English"],
  ["Nothing comes of nothing", "Latin"],
  ["Nothing dries sooner than a tear", "English"],
  ["Nothing in excess", "Latin"],
  ["Nothing is certain but death and taxes", "English"],
  ["Nothing is impossible to a willing heart", "English"],
  ["Nothing succeeds like success", "English"],
  ["Nothing ventured, nothing gained", "English"],
  ["Oil and water don't mix", "English"],
  ["Old friends and old wine are best", "English"],
  ["Old habits die hard", "English"],
  ["Old sins cast long shadows", "English"],
  ["Once bitten, twice shy", "English"],
  ["One cannot be in two places at once", "English"],
  ["One good turn deserves another", "English"],
  ["One half of the world does not know how the other half lives", "English"],
  ["One hand washes the other", "English"],
  ["One hour today is worth two tomorrow", "English"],
  ["One law for the rich and another for the poor", "English"],
  ["One man's loss is another man's gain", "English"],
  ["One man's meat is another man's poison", "English"],
  ["One nail drives out another", "English"],
  ["One swallow does not make a summer", "English"],
  ["One volunteer is worth two pressed men", "English"],
  ["One wedding brings another", "English"],
  ["Opportunity knocks but once", "English"],
  ["Opportunity makes the thief", "English"],
  ["Out of debt, out of danger", "English"],
  ["Out of sight, out of mind", "English"],
  ["Out of the frying pan into the fire", "English"],
  ["Out of the mouths of babes", "English"],
  ["Paddle your own canoe", "English"],
  ["Patience is a virtue", "English"],
  ["Penny wise, pound foolish", "English"],
  ["People who live in glass houses shouldn't throw stones", "English"],
  ["Physician, heal thyself", "English"],
  ["Possession is nine points of the law", "English"],
  ["Poverty is no disgrace", "English"],
  ["Practice makes perfect", "English"],
  ["Practice what you preach", "English"],
  ["Praise the bridge that carries you over", "English"],
  ["Prevention is better than cure", "English"],
  ["Pride goes before a fall", "English"],
  ["Procrastination is the thief of time", "English"],
  ["Promises are like piecrust, made to be broken", "English"],
  ["Put a beggar on horseback and he'll ride to the devil", "English"],
  ["Put your best foot forward", "English"],
  ["Put your own house in order", "English"],
  ["Put your shoulder to the wheel", "English"],
  ["Rain before seven, fine before eleven", "English"],
  ["Rats desert a sinking ship", "English"],
  ["Red sky at night, shepherd's delight", "English"],
  ["Red sky in the morning, shepherd's warning", "English"],
  ["Remember you must die", "Latin"],
  ["Repetition is the mother of learning", "Latin"],
  ["Revenge is sweet", "English"],
  ["Rob Peter to pay Paul", "English"],
  ["Rome was not built in a day", "English"],
  ["Save for a rainy day", "English"],
  ["Scratch my back and I'll scratch yours", "English"],
  ["Second thoughts are best", "English"],
  ["Seeing is believing", "English"],
  ["Seek and you shall find", "English"],
  ["Seize the day", "Latin"],
  ["Self-preservation is the first law of nature", "English"],
  ["Set a thief to catch a thief", "English"],
  ["Share and share alike", "English"],
  ["Short reckonings make long friends", "English"],
  ["Silence gives consent", "Latin"],
  ["Silence is golden", "English"],
  ["Slow and steady wins the race", "English"],
  ["Slow but sure", "English"],
  ["Small leaks sink great ships", "English"],
  ["Something is better than nothing", "English"],
  ["Soon ripe, soon rotten", "English"],
  ["Sow the wind and reap the whirlwind", "English"],
  ["Spare the rod and spoil the child", "English"],
  ["Speak of the devil and he appears", "English"],
  ["Speech is silver, silence is golden", "English"],
  ["Stand on your own two feet", "English"],
  ["Still waters run deep", "English"],
  ["Stolen fruit is the sweetest", "English"],
  ["Strike while the iron is hot", "English"],
  ["Sufficient unto the day is the evil thereof", "English"],
  ["Take the bull by the horns", "English"],
  ["Take the rough with the smooth", "English"],
  ["Talk is cheap", "English"],
  ["The apple never falls far from the tree", "English"],
  ["The best of friends must part", "English"],
  ["The best things come in small packages", "English"],
  ["The best-laid schemes o' mice an' men gang aft agley", "Scottish"],
  ["The bigger they are, the harder they fall", "English"],
  ["The blind leading the blind", "English"],
  ["The bread never falls but on the buttered side", "English"],
  ["The cobbler always wears the worst shoes", "English"],
  ["The darkest hour is just before the dawn", "English"],
  ["The devil can quote scripture for his purpose", "English"],
  ["The devil finds work for idle hands", "English"],
  ["The devil is not so black as he is painted", "English"],
  ["The devil looks after his own", "English"],
  ["The die is cast", "Latin"],
  ["The early bird catches the worm", "English"],
  ["The end crowns the work", "English"],
  ["The end justifies the means", "English"],
  ["The exception proves the rule", "Latin"],
  ["The eyes are the window of the soul", "English"],
  ["The fat is in the fire", "English"],
  ["The first blow is half the battle", "English"],
  ["The first step is the hardest", "English"],
  ["The good die young", "English"],
  ["The grass is always greener on the other side", "English"],
  ["The hand that rocks the cradle rules the world", "English"],
  ["The higher the monkey climbs, the more he shows his tail", "English"],
  ["The last straw breaks the camel's back", "English"],
  ["The longest day must have an end", "English"],
  ["The longest way round is the shortest way home", "English"],
  ["The love of money is the root of all evil", "English"],
  ["The mills of God grind slowly", "English"],
  ["The more the merrier", "English"],
  ["The more you get, the more you want", "English"],
  ["The mountain labors and brings forth a mouse", "Latin"],
  ["The nearer the bone, the sweeter the meat", "English"],
  ["The pen is mightier than the sword", "English"],
  ["The pitcher goes often to the well but is broken at last", "English"],
  ["The pot calling the kettle black", "English"],
  ["The proof of the pudding is in the eating", "English"],
  ["The race is not always to the swift", "English"],
  ["The road to hell is paved with good intentions", "English"],
  ["The shoemaker's son always goes barefoot", "English"],
  ["The show must go on", "English"],
  ["The spirit is willing but the flesh is weak", "English"],
  ["The sun shines on everyone", "Latin"],
  ["The tailor makes the man", "English"],
  ["The tongue is not steel yet it cuts", "English"],
  ["The unexpected always happens", "English"],
  ["The voice of the people is the voice of God", "Latin"],
  ["The weakest go to the wall", "English"],
  ["The welfare of the people is the supreme law", "Latin"],
  ["The wish is father to the thought", "English"],
  ["There are as good fish in the sea as ever came out of it", "English"],
  ["There is a remedy for everything except death", "English"],
  ["There is a time and a place for everything", "English"],
  ["There is danger in delay", "Latin"],
  ["There is honor among thieves", "English"],
  ["There is no accounting for taste", "English"],
  ["There is no fool like an old fool", "English"],
  ["There is no place like home", "English"],
  ["There is no royal road to learning", "English"],
  ["There is nothing new under the sun", "English"],
  ["There is safety in numbers", "English"],
  ["There's many a good tune played on an old fiddle", "English"],
  ["There's many a slip 'twixt the cup and the lip", "English"],
  ["There's nowt so queer as folk", "English"],
  ["Threatened men live long", "English"],
  ["Throw dirt enough and some will stick", "English"],
  ["Throw out a sprat to catch a mackerel", "English"],
  ["Thus passes the glory of the world", "Latin"],
  ["Time and tide wait for no man", "English"],
  ["Time flies", "Latin"],
  ["Time heals all wounds", "English"],
  ["Time is money", "English"],
  ["Time tries all", "English"],
  ["Time will tell", "English"],
  ["Times change and we change with them", "Latin"],
  ["To each his own", "English"],
  ["To err is human, to forgive divine", "Latin"],
  ["To the victor belong the spoils", "English"],
  ["Tomorrow is another day", "English"],
  ["Tomorrow never comes", "English"],
  ["Too many cooks spoil the broth", "English"],
  ["Touch pitch and you will be defiled", "English"],
  ["Travel broadens the mind", "English"],
  ["Trust not a new friend nor an old enemy", "English"],
  ["Truth is stranger than fiction", "English"],
  ["Truth lies at the bottom of a well", "English"],
  ["Truth will out", "English"],
  ["Two blacks do not make a white", "English"],
  ["Two heads are better than one", "English"],
  ["Two of a trade never agree", "English"],
  ["Two wrongs don't make a right", "English"],
  ["Two's company, three's a crowd", "English"],
  ["Union is strength", "English"],
  ["Variety is the spice of life", "English"],
  ["Virtue is its own reward", "English"],
  ["Virtue stands in the middle", "Latin"],
  ["Walls have ears", "English"],
  ["Walnuts and pears you plant for your heirs", "English"],
  ["Wanton kittens make sober cats", "English"],
  ["Waste not, want not", "English"],
  ["We must learn to walk before we can run", "English"],
  ["Well begun is half done", "English"],
  ["What can't be cured must be endured", "English"],
  ["What goes up must come down", "English"],
  ["What is bred in the bone will come out in the flesh", "English"],
  ["What the eye doesn't see, the heart doesn't grieve over", "English"],
  ["What you lose on the swings you gain on the roundabouts", "English"],
  ["What's done cannot be undone", "English"],
  ["What's fur ye'll no go by ye", "Scottish"],
  ["What's sauce for the goose is sauce for the gander", "English"],
  ["When all fruit fails, welcome haws", "English"],
  ["When in doubt, do nowt", "English"],
  ["When in Rome, do as the Romans do", "English"],
  ["When one door shuts, another opens", "English"],
  ["When poverty comes in at the door, love flies out the window", "English"],
  ["When the cat's away, the mice will play", "English"],
  ["When thieves fall out, honest men come by their own", "English"],
  ["Where bees are, there is honey", "English"],
  ["Where God builds a church, the devil builds a chapel", "English"],
  ["Where ignorance is bliss, 'tis folly to be wise", "English"],
  ["Where one is well, there is one's country", "Latin"],
  ["Where there's a will, there's a way", "English"],
  ["Where there's muck there's brass", "English"],
  ["While the grass grows, the steed starves", "English"],
  ["While there's life there's hope", "English"],
  ["Who chatters to you will chatter of you", "English"],
  ["Who keeps company with the wolf will learn to howl", "English"],
  ["Who will watch the watchmen", "Latin"],
  ["Whom the gods would destroy they first make mad", "Latin"],
  ["Wilful waste makes woeful want", "English"],
  ["Wine has drowned more men than the sea", "English"],
  ["Wise men learn by others' mistakes, fools by their own", "English"],
  ["Wonders will never cease", "English"],
  ["Work conquers all", "Latin"],
  ["Ye cannae put an auld heid on young shoothers", "Scottish"],
  ["You can have too much of a good thing", "English"],
  ["You can lead a horse to water, but you cannot make him drink", "English"],
  ["You cannot get a quart into a pint pot", "English"],
  ["You cannot have your cake and eat it", "English"],
  ["You cannot make a silk purse out of a sow's ear", "English"],
  ["You cannot make an omelette without breaking eggs", "English"],
  ["You cannot run with the hare and hunt with the hounds", "English"],
  ["You cannot serve God and mammon", "English"],
  ["You cannot shift an old tree without it dying", "English"],
  ["You cannot teach an old dog new tricks", "English"],
  ["You get what you pay for", "English"],
  ["You made your bed, now lie in it", "English"],
  ["You never know what you can do till you try", "English"],
  ["You never miss the water till the well runs dry", "English"],
  ["You pays your money and you takes your choice", "English"],
  ["You reap what you sow", "English"],
  ["Young men may die, old men must", "English"],
  ["Youth and age will never agree", "English"],
] as const satisfies ReadonlyArray<readonly [string, "English" | "Scottish" | "Latin"]>;

export const catalog = createCatalog(ENTRIES.map(([text, origin]) => ({ text, origin })));
